cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAUZZQUTZTNUCAPMDB
      secret-key: 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
    end-point:
      uri-fifo: https://sqs.ap-southeast-1.amazonaws.com/330277625446/MyFIFOQueue.fifo
      uri-simple: https://sqs.ap-southeast-1.amazonaws.com/330277625446/SimpleQueue